#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/ctries_go
  
  blListGen \
    -d ../ctries_go \
    -1L  \
    -u $DVCZ_UDIR \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
