#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/go/src/github.com/jddixon/ctries_go
  
  echo "\nLOGIC FOR INSTALLING GO SCRIPTS IS NOT IMPLEMENTED"
  
else
  echo "DEV_BASE is not defined"
fi
